CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SLEEP=y

# PAW3395 sensor
CONFIG_SPI=y
CONFIG_ZMK_POINTING=y
CONFIG_PAW3395=y
CONFIG_REPORT_CPI=y

# VFX RGB
CONFIG_VFX_RGBLED_INDICATOR=y
CONFIG_VFX_LDO_PIN=y
CONFIG_VFX_CHRG_PIN=y

# Encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Low latency BLE for mouse
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
